name: mosi2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  # ğŸ¨ Simply Now Design System
  flutter_simply_design_system: # Alias personalizado
    git:
      url: git@github.com:be-yapsi/flutter_simply_design_system.git

  # ğŸ“Œ Flutter SDK
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ğŸŒ Networking
  dio: ^5.8.0+1

  # ğŸ¯ State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # ğŸ”§ Utilities
  intl: ^0.19.0
  logger: ^2.5.0
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.5.1
  flutter_secure_storage: ^9.2.4

  # ğŸ¨ UI/UX
  flutter_svg: ^2.0.17
  material_symbols_icons: ^4.2801.1
  lottie: ^3.3.1
  qr_flutter: ^4.1.0
  screen_brightness: ^2.1.2

  # âš™ï¸ Environment Configuration
  flutter_dotenv: ^5.2.1

  # ğŸ§­ Routing
  go_router: ^14.7.2

  # ğŸ—ï¸ Code Generation
  equatable: ^2.0.7
  freezed_annotation: ^2.4.4

  # ğŸ“± Native Features
  flutter_native_splash: ^2.4.4
  local_auth: ^2.3.0

  # ğŸ› ï¸ Test & Debugging
  camera: ^0.11.1
  google_mlkit_text_recognition: ^0.14.0
  image: ^4.5.2
  sensors_plus: ^6.1.1

  # ğŸ›œ Google APIs
  googleapis: ^13.2.0
  googleapis_auth: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: 753BBD

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/animations/
    - assets/dialogflow/
    - assets/fonts/
    - assets/icons/
    - assets/illustrations/
    - assets/images/
    - assets/jsons/
    - assets/lang/
    - assets/logos/partners/
    - assets/logos/proyect/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
